docker-front/web-app/ups/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('upsapp.urls')),
    path('admin/', admin.site.urls),
]

docker-front/web-app/upsapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.contrib import admin
from . import views
from upsapp.views import home_view, signup_view, list_view, pkg_detail_view, feedback_view, profile_update_view

app_name = 'upsapp'
urlpatterns = [
    path('', home_view, name = 'home'),
    path('signup/', signup_view, name = 'signup'),
    path('logout/', auth_views.LogoutView.as_view(template_name='upsapp/logout.html'), name = 'logout'),
    path('login/', auth_views.LoginView.as_view(template_name='upsapp/login.html'), name = 'login'),
    path('update/', profile_update_view, name = 'update'),
    path('list/', list_view.as_view(), name = 'list'),
    path('pkg/<int:pk>/', pkg_detail_view.as_view(), name = 'detail'),
    path('feedback/', feedback_view.as_view(), name = 'feedback'),
]

docker-front/web-app/upsapp/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser

SATISFY_CHOICES = (
       ('VERY_SATISFIED', 'Very Satisfied'),
       ('SATISFIED', 'Satisfied'),
       ('OK','OK'),
       ('DISATISFIED', 'Disatisfied'),
       ('VERY_DISATISFIED', 'Very Disatisfied'),
    )

class ups_user(AbstractUser):
    user_name = models.CharField(max_length = 50, verbose_name = 'Your Name')

class ups_package(models.Model):
    package_id = models.IntegerField()
    x = models.IntegerField(default = 0)
    y = models.IntegerField(default = 0)
    owner = models.CharField(max_length = 50)
    status = models.CharField(max_length = 50)
    product_name = models.CharField(max_length = 50)
    truck_id = models.IntegerField()
    def get_absolute_url(self):
        return reverse('upsapp:detail', kwargs={'pk': self.pk})

class ups_truck(models.Model):
    truck_id = models.IntegerField()
    status = models.CharField(max_length = 50)

class ups_feedback(models.Model):
    satisfied = models.CharField(max_length=50, choices=SATISFY_CHOICES, default = 'SATISFIED')
    content = models.CharField(max_length = 300)
    def get_absolute_url(self):
        return reverse('upsapp:home')

docker-front/web-app/upsapp/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from .models import ups_user

class UserSignupForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = ups_user
        fields = ['username', 'email', 'password1', 'password2']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = ups_user
        fields = ['email']

docker-front/web-app/upsapp/views.py
from django.shortcuts import render, redirect
from .forms import UserSignupForm, ProfileUpdateForm
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from .models import ups_user, ups_package, ups_truck, ups_feedback
from django.views.generic import CreateView, ListView, DetailView
from django.db.models import Q
from django.conf import settings

def home_view(request):
    qs = ups_package.objects.all()
    pkg_id = request.GET.get('pkgnum')
    if pkg_id != '':
        qs = qs.filter(
                Q(package_id = pkg_id)
            ).distinct()
    else:
        qs = None
    context = {
        'queryset' : qs
    }
    return render(request, 'upsapp/home.html', context)

def signup_view(request):
    if request.method == "POST":
        form = UserSignupForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, f'Successfully Sign Up!')
            return redirect('upsapp:login')
    else:
        form = UserSignupForm
    return render(request, 'upsapp/signup.html', {'form': form})

@login_required
def profile_update_view(request):
    if request.method == "POST":
        form = ProfileUpdateForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, f'Account profile updated!')
            return redirect('upsapp:home')
    else:
        form = ProfileUpdateForm(instance=request.user)
    return render(request, 'upsapp/update.html', {'form': form}) 

class list_view(LoginRequiredMixin, ListView):
    model = ups_package
    context_object_name = 'packages'
    template_name = 'upsapp/list.html'
    def get_queryset(self):
        return ups_package.objects.filter(owner = self.request.user.username)

class pkg_detail_view(DetailView):
    model = ups_package

class feedback_view(SuccessMessageMixin, CreateView):
    model = ups_feedback
    fields = ['satisfied', 'content']
    template_name = 'upsapp/feedback.html'
    success_message = "Thanks for your feedback!"

docker-front/web-app/upsapp/templates/upsapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'upsapp/main.css' %}">

    {% if title %}
        <title>UPS - {{ title }}</title>
    {% else %}
        <title>UPS</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand" href="{% url 'upsapp:home'%}">
            <img src="{% static "upsapp/UPS_logo.svg" %}"  width="70" height="70" class="d-inline-block align-top" alt="">
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              
            </div>
            
            <!-- Navbar Right Side -->
            {% if user.is_authenticated %}
            <div class="navbar-nav">
              <a class="nav-item nav-link">Welcome, {{ user.username }} </a>
              <a class="nav-item nav-link" href="{% url 'upsapp:logout'%}">Logout</a>
            </div>
            {% else %}
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="{% url 'upsapp:login'%}">Login</a>
              <a class="nav-item nav-link" href="{% url 'upsapp:signup'%}">Signup</a>
            </div>
            {% endif %}
          </div>
        </div>
        <a class="feedback-btn btn btn-secondary float-right" href="{% url 'upsapp:feedback'%}"> > Feedback </a>
      </nav>
    </header>
    <br><br>
    <main role="main" class="container pt-3">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
      {% block content %}{% endblock %}
 
      </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

docker-front/web-app/upsapp/templates/upsapp/feedback.html
{% extends 'upsapp/base.html' %}

{% block title %}Feedback{% endblock %}
{% block content %}
  <h4>Feedback</h4>
  <br>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-outline-primary btn-sm" type="submit">Submit</button>
  </form>
{% endblock %}

docker-front/web-app/upsapp/templates/upsapp/home.html
{% extends 'upsapp/base.html' %}

{% block title %}Welcome to UPS!{% endblock %}
{% block content %}
<br>

<div class="row">
    <div class="col">
        <div class="input-group mb-3">
            
            <form method="get">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="inputGroup-sizing-default">Tracking Number</span>
                    <input type="text" class="form-control" name="pkgnum" id="pkg_id" aria-label="Default" aria-describedby="inputGroup-sizing-default" size="50">
                <button class="btn btn-outline-secondary" type="submit">Track</button>
                </div>
            </form>
            <br><br>
            <table class="table table-hover">
                <thead>
                    <tr>
                    <th scope="col">Tracking Number</th>
                    <th scope="col">Status</th>
                    <th scope="col">Detail</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pkg in queryset %}
                        <tr>
                            <td>{{ pkg.package_id }}</td>
                            <td>{{ pkg.status }}</td>
                            <td>
                                <a class="btn btn-outline-success btn-sm" href="{% url 'upsapp:detail' pkg.id %}" role="button">View Detail</a>
                            </td>
                        </tr>
                    {% endfor%}
                </tbody>
            </table>
        </div>
    </div>

  <div class="col">
    <div class="card" style="width: 30rem;">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-8">
                    <p class="card-text">
                    <strong>Introducing UPS Account.</strong>
                    <br>
                    Track all your shipments like a pro
                    <br>
                    </p>
                </div>
                <div class="col-sm-4">
                    {% if not user.is_authenticated %}
                        <a href="{% url 'upsapp:signup'%}" class="btn btn-outline-success btn-md">Sign Up Now!</a>
                    {% endif %}
                </div>
            </div>
            <hr>

            {% if user.is_authenticated %}
                You already signed in.
                <br><br>       
                <div class="btn-group-vertical">
                    <a href="{% url 'upsapp:update'%}" class="btn btn-outline-success btn-sm">Update Email</a>
                    <a href="{% url 'upsapp:list'%}" class="btn btn-outline-success btn-sm">Manage all my packages</a>
                </div>

            {% else %}
                Already Have an Account? <a href={% url 'upsapp:login'%}> Log In </a>
            {% endif %}

        </div>
        </div>
    </div>
</div>

{% endblock %}

docker-front/web-app/upsapp/templates/upsapp/list.html
{% extends "upsapp/base.html" %}

{% block content %}
<main role="main" class="container pt-3">

<h3>Welcome, {{ user.username }}</h3>
<br>
<table class="table table-hover">
    <thead>
        <tr>
        <th scope="col">Tracking Number</th>
        <th scope="col">Product Name</th>
        <th scope="col">Status</th>
        <th scope="col">Detail</th>
        </tr>
    </thead>
    <tbody>
        {% for pkg in packages %}
            <tr>
                <td>{{ pkg.package_id }}</td>
                <td>{{ pkg.product_name }}</td>
                <td>{{ pkg.status }}</td>
                <td>
                    <a class="btn btn-outline-success btn-sm" href="{% url 'upsapp:detail' pkg.id %}" role="button">View Detail</a>
                </td>
            </tr>
        {% endfor%}
    </tbody>
</table>

{% endblock content %}

docker-front/web-app/upsapp/templates/upsapp/login.html
{% extends 'upsapp/base.html' %}

{% block title %}Login{% endblock %}
{% block content %}
  <h4>Login</h4>
  <br>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-outline-primary btn-sm" type="submit">Log In</button>
  </form>
  <hr>
  No Account?  <a href="{% url 'upsapp:signup' %}"> Sign Up</a>
{% endblock %}

docker-front/web-app/upsapp/templates/upsapp/logout.html
{% extends 'upsapp/base.html' %}

{% block title %}Log Out{% endblock %}
{% block content %}
  <h4>Successfully Logged Out!</h4>
  <hr>
  <a href="{% url 'upsapp:login' %}">Log In Again</a>
{% endblock %}

docker-front/web-app/upsapp/templates/upsapp/profile.html
{% extends "upsapp/base.html" %}

{% block content %}
<main role="main" class="container pt-3">

<h3>Welcome, {{ user.username }}</h3>
<br>
<table class="table table-hover">
    <thead>
        <tr>
        <th scope="col">Tracking Number</th>
        <th scope="col">Product Name</th>
        <th scope="col">Status</th>
        <th scope="col">Detail</th>
        </tr>
    </thead>
    <tbody>
        {% for pkg in packages %}
            <tr>
                <td>{{ pkg.package_id }}</td>
                <td>{{ pkg.product_name }}</td>
                <td>{{ pkg.status }}</td>
                <td>
                    <a class="btn btn-outline-success btn-sm" href="{% url 'upsapp:detail' pkg.id %}" role="button">View Detail</a>
                </td>
            </tr>
        {% endfor%}
    </tbody>
</table>

{% endblock content %}

docker-front/web-app/upsapp/templates/upsapp/signup.html
{% extends 'upsapp/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<h4>Sign Up Now!</h4>
<hr>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-outline-success btn-sm" type="submit">Sign Up</button>
</form>
<hr>
Already Have an Account? <a href={% url 'upsapp:login'%}> Log In </a>
{% endblock %}

docker-front/web-app/upsapp/templates/upsapp/update.html
{% extends 'upsapp/base.html' %}

{% block title %}Update Information{% endblock %}

{% block content %}
  <h4>Update Information</h4>
  <br>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-outline-primary btn-sm" type="submit">Update</button>
  </form>
{% endblock %}

docker-front/web-app/upsapp/templates/upsapp/ups_package_detail.html
{% extends "upsapp/base.html" %}
{% block content %}

<h4>Tracking Number {{ object.package_id }}</h4>
<ul class="list-group">
    <li class="list-group-item"><strong>Owner:</strong> {{ object.owner }}</li>
    <li class="list-group-item"><strong>Status:</strong> {{ object.status }}</li>
    <li class="list-group-item"><strong>Product Name:</strong> {{ object.product_name }}</li>
    <li class="list-group-item"><strong>Truck id:</strong> {{ object.truck_id }}</li>
</ul>
<br>
<a class="btn btn-outline-success btn-sm" href="{{request.META.HTTP_REFERER|escape}}" role="button">Go Back</a>

{% endblock content %}